# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03b6eeb929814aa8d5b82ba62eebca9fe8abbe8a39ab146d54fa20d64347d247cd5c9ac8dd0cb071871e3a017fc1f16cc223a0ca40057635df4c28ee98876fce

test:
  secret_key_base: 728cb734ed87cc4b72a464c59d1d6f178649cc747d12861c905a9866b5b20ff14154bf3d29f724d3955106705ca9385fedceb028a126bca815266fbce66c4232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
